### ISSUE TITLE
Updating the RDPC Workflow UI

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-ui#61]
This epic will consist of a short project completed by @mistryrn.  Its scope will include:

### Adding Security
- [x] Add Ego Login
- [x] Add Authorization for the UI based on 2 profiles (READ - RDPC Member WRITE - RDPC Admin)
### Adding UI Enhancements to move any debugging work from the Model T UI to the Workflow UI 
- [ ] Add new columns to the workflow 
### Design updates for ARGO (branding)
-  [x] New logo that isn't CARGO
### Stats and Charts about the Workflows
- [ ] chart of all running wfs, broken down by type at the rdpc

**Comment by rosibaj** [comment]
Closing as the scope of time/work available was completed. thanks @mistryrn !!
